Fix a mis-aligned else that causes a crash
mistralai/mistral-finetune pull request #91
Opened 2024-08-19 00:41 UTC by mkserge

Fixes an issue introduced in the commit `984ca2dc` where the `else` is misaligned causing the following crash when running data validation tool.

```
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 159, in _get_module_details
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ec2-user/workspace/mistral/mistral-finetune/utils/validate_data.py", line 113
    else:
TabError: inconsistent use of tabs and spaces in indentation
```

2024-08-20 08:02 UTC, pg56714 requested changes
Thank you for your fix. However, it seems that the code has not actually changed.

Therefore, this issue can be closed directly.

2024-08-20 08:04 UTC, pg56714 approved these changes
On GitHub, it appears that the code has not actually changed, but when downloaded, the issue does exist.

2024-08-20 12:17 UTC, mkserge commented
Github does not render the diff correctly, unfortunately, but the fix is correct. You can copy the diff into a text editor and see the difference.

2024-09-02 20:08 UTC, patrickvonplaten commented
Thanks!

2024-09-02 20:09 UTC, merged